// UserModel.js
import mongoose from 'mongoose';

const UserSchema = new mongoose.Schema({
  _id: String,
  username: String,
  title: String,
  firstName: String,
  lastName: String,
  cpf: String,
  documentNumber: String,
  countryCode: String,
  phoneNumber: String,
  email: String,
  acceptEmails: Boolean,
  street: String,
  number: String,
  complement: String,
  district: String,
  city: String,
  state: String,
  zipcode: String,
  birthDate: mongoose.Schema.Types.Mixed,
  groupIds: Array,
  type: String,
  createdAt: Date,
  slug: String,
  updatedAt: Date,
  titleSortified: String,
  highSearchText: String,
  highSearchWords: Array,
  lowSearchText: String,
  searchSummary: String,
  viewGroupsIds: Array,
  viewUsersIds: Array,
  excludeViewGroupsIds: Array,
  editGroupsIds: Array,
  editUsersIds: Array,
  docPermissions: Array,
  group: String,
  lastLogin: Date,
}, { collection: 'aposDocs' });

export const UserModel = mongoose.models.UserModel || mongoose.model('UserModel', UserSchema);
